/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:39:19 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.pollimageendpoint.model;

/**
 * Model definition for PollImage.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the pollimageendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class PollImage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descrizione;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key keyImg;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key keyPI;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key keyPoll;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescrizione() {
    return descrizione;
  }

  /**
   * @param descrizione descrizione or {@code null} for none
   */
  public PollImage setDescrizione(java.lang.String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKeyImg() {
    return keyImg;
  }

  /**
   * @param keyImg keyImg or {@code null} for none
   */
  public PollImage setKeyImg(Key keyImg) {
    this.keyImg = keyImg;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKeyPI() {
    return keyPI;
  }

  /**
   * @param keyPI keyPI or {@code null} for none
   */
  public PollImage setKeyPI(Key keyPI) {
    this.keyPI = keyPI;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKeyPoll() {
    return keyPoll;
  }

  /**
   * @param keyPoll keyPoll or {@code null} for none
   */
  public PollImage setKeyPoll(Key keyPoll) {
    this.keyPoll = keyPoll;
    return this;
  }

  @Override
  public PollImage set(String fieldName, Object value) {
    return (PollImage) super.set(fieldName, value);
  }

  @Override
  public PollImage clone() {
    return (PollImage) super.clone();
  }

}
