/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-27 at 09:41:58 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.myimageendpoint;

/**
 * Service definition for Myimageendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link MyimageendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Myimageendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the myimageendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "myimageendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Myimageendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Myimageendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getMyImage".
   *
   * This request holds the parameters needed by the the myimageendpoint server.  After setting any
   * optional parameters, call the {@link GetMyImage#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetMyImage getMyImage(java.lang.Long id) throws java.io.IOException {
    GetMyImage result = new GetMyImage(id);
    initialize(result);
    return result;
  }

  public class GetMyImage extends MyimageendpointRequest<com.example.googletutorial2.myimageendpoint.model.MyImage> {

    private static final String REST_PATH = "myimage/{id}";

    /**
     * Create a request for the method "getMyImage".
     *
     * This request holds the parameters needed by the the myimageendpoint server.  After setting any
     * optional parameters, call the {@link GetMyImage#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetMyImage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetMyImage(java.lang.Long id) {
      super(Myimageendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.myimageendpoint.model.MyImage.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetMyImage setAlt(java.lang.String alt) {
      return (GetMyImage) super.setAlt(alt);
    }

    @Override
    public GetMyImage setFields(java.lang.String fields) {
      return (GetMyImage) super.setFields(fields);
    }

    @Override
    public GetMyImage setKey(java.lang.String key) {
      return (GetMyImage) super.setKey(key);
    }

    @Override
    public GetMyImage setOauthToken(java.lang.String oauthToken) {
      return (GetMyImage) super.setOauthToken(oauthToken);
    }

    @Override
    public GetMyImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetMyImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetMyImage setQuotaUser(java.lang.String quotaUser) {
      return (GetMyImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetMyImage setUserIp(java.lang.String userIp) {
      return (GetMyImage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetMyImage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetMyImage set(String parameterName, Object value) {
      return (GetMyImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertMyImage".
   *
   * This request holds the parameters needed by the the myimageendpoint server.  After setting any
   * optional parameters, call the {@link InsertMyImage#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.myimageendpoint.model.MyImage}
   * @return the request
   */
  public InsertMyImage insertMyImage(com.example.googletutorial2.myimageendpoint.model.MyImage content) throws java.io.IOException {
    InsertMyImage result = new InsertMyImage(content);
    initialize(result);
    return result;
  }

  public class InsertMyImage extends MyimageendpointRequest<com.example.googletutorial2.myimageendpoint.model.MyImage> {

    private static final String REST_PATH = "myimage";

    /**
     * Create a request for the method "insertMyImage".
     *
     * This request holds the parameters needed by the the myimageendpoint server.  After setting any
     * optional parameters, call the {@link InsertMyImage#execute()} method to invoke the remote
     * operation. <p> {@link InsertMyImage#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.myimageendpoint.model.MyImage}
     * @since 1.13
     */
    protected InsertMyImage(com.example.googletutorial2.myimageendpoint.model.MyImage content) {
      super(Myimageendpoint.this, "POST", REST_PATH, content, com.example.googletutorial2.myimageendpoint.model.MyImage.class);
    }

    @Override
    public InsertMyImage setAlt(java.lang.String alt) {
      return (InsertMyImage) super.setAlt(alt);
    }

    @Override
    public InsertMyImage setFields(java.lang.String fields) {
      return (InsertMyImage) super.setFields(fields);
    }

    @Override
    public InsertMyImage setKey(java.lang.String key) {
      return (InsertMyImage) super.setKey(key);
    }

    @Override
    public InsertMyImage setOauthToken(java.lang.String oauthToken) {
      return (InsertMyImage) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertMyImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertMyImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertMyImage setQuotaUser(java.lang.String quotaUser) {
      return (InsertMyImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertMyImage setUserIp(java.lang.String userIp) {
      return (InsertMyImage) super.setUserIp(userIp);
    }

    @Override
    public InsertMyImage set(String parameterName, Object value) {
      return (InsertMyImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMyImage".
   *
   * This request holds the parameters needed by the the myimageendpoint server.  After setting any
   * optional parameters, call the {@link ListMyImage#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListMyImage listMyImage() throws java.io.IOException {
    ListMyImage result = new ListMyImage();
    initialize(result);
    return result;
  }

  public class ListMyImage extends MyimageendpointRequest<com.example.googletutorial2.myimageendpoint.model.CollectionResponseMyImage> {

    private static final String REST_PATH = "myimage";

    /**
     * Create a request for the method "listMyImage".
     *
     * This request holds the parameters needed by the the myimageendpoint server.  After setting any
     * optional parameters, call the {@link ListMyImage#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListMyImage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListMyImage() {
      super(Myimageendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.myimageendpoint.model.CollectionResponseMyImage.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMyImage setAlt(java.lang.String alt) {
      return (ListMyImage) super.setAlt(alt);
    }

    @Override
    public ListMyImage setFields(java.lang.String fields) {
      return (ListMyImage) super.setFields(fields);
    }

    @Override
    public ListMyImage setKey(java.lang.String key) {
      return (ListMyImage) super.setKey(key);
    }

    @Override
    public ListMyImage setOauthToken(java.lang.String oauthToken) {
      return (ListMyImage) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMyImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMyImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMyImage setQuotaUser(java.lang.String quotaUser) {
      return (ListMyImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMyImage setUserIp(java.lang.String userIp) {
      return (ListMyImage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListMyImage setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListMyImage setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListMyImage set(String parameterName, Object value) {
      return (ListMyImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeMyImage".
   *
   * This request holds the parameters needed by the the myimageendpoint server.  After setting any
   * optional parameters, call the {@link RemoveMyImage#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveMyImage removeMyImage(java.lang.Long id) throws java.io.IOException {
    RemoveMyImage result = new RemoveMyImage(id);
    initialize(result);
    return result;
  }

  public class RemoveMyImage extends MyimageendpointRequest<Void> {

    private static final String REST_PATH = "myimage/{id}";

    /**
     * Create a request for the method "removeMyImage".
     *
     * This request holds the parameters needed by the the myimageendpoint server.  After setting any
     * optional parameters, call the {@link RemoveMyImage#execute()} method to invoke the remote
     * operation. <p> {@link RemoveMyImage#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveMyImage(java.lang.Long id) {
      super(Myimageendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveMyImage setAlt(java.lang.String alt) {
      return (RemoveMyImage) super.setAlt(alt);
    }

    @Override
    public RemoveMyImage setFields(java.lang.String fields) {
      return (RemoveMyImage) super.setFields(fields);
    }

    @Override
    public RemoveMyImage setKey(java.lang.String key) {
      return (RemoveMyImage) super.setKey(key);
    }

    @Override
    public RemoveMyImage setOauthToken(java.lang.String oauthToken) {
      return (RemoveMyImage) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveMyImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveMyImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveMyImage setQuotaUser(java.lang.String quotaUser) {
      return (RemoveMyImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveMyImage setUserIp(java.lang.String userIp) {
      return (RemoveMyImage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveMyImage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveMyImage set(String parameterName, Object value) {
      return (RemoveMyImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateMyImage".
   *
   * This request holds the parameters needed by the the myimageendpoint server.  After setting any
   * optional parameters, call the {@link UpdateMyImage#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.myimageendpoint.model.MyImage}
   * @return the request
   */
  public UpdateMyImage updateMyImage(com.example.googletutorial2.myimageendpoint.model.MyImage content) throws java.io.IOException {
    UpdateMyImage result = new UpdateMyImage(content);
    initialize(result);
    return result;
  }

  public class UpdateMyImage extends MyimageendpointRequest<com.example.googletutorial2.myimageendpoint.model.MyImage> {

    private static final String REST_PATH = "myimage";

    /**
     * Create a request for the method "updateMyImage".
     *
     * This request holds the parameters needed by the the myimageendpoint server.  After setting any
     * optional parameters, call the {@link UpdateMyImage#execute()} method to invoke the remote
     * operation. <p> {@link UpdateMyImage#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.myimageendpoint.model.MyImage}
     * @since 1.13
     */
    protected UpdateMyImage(com.example.googletutorial2.myimageendpoint.model.MyImage content) {
      super(Myimageendpoint.this, "PUT", REST_PATH, content, com.example.googletutorial2.myimageendpoint.model.MyImage.class);
    }

    @Override
    public UpdateMyImage setAlt(java.lang.String alt) {
      return (UpdateMyImage) super.setAlt(alt);
    }

    @Override
    public UpdateMyImage setFields(java.lang.String fields) {
      return (UpdateMyImage) super.setFields(fields);
    }

    @Override
    public UpdateMyImage setKey(java.lang.String key) {
      return (UpdateMyImage) super.setKey(key);
    }

    @Override
    public UpdateMyImage setOauthToken(java.lang.String oauthToken) {
      return (UpdateMyImage) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateMyImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateMyImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateMyImage setQuotaUser(java.lang.String quotaUser) {
      return (UpdateMyImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateMyImage setUserIp(java.lang.String userIp) {
      return (UpdateMyImage) super.setUserIp(userIp);
    }

    @Override
    public UpdateMyImage set(String parameterName, Object value) {
      return (UpdateMyImage) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Myimageendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Myimageendpoint}. */
    @Override
    public Myimageendpoint build() {
      return new Myimageendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link MyimageendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setMyimageendpointRequestInitializer(
        MyimageendpointRequestInitializer myimageendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(myimageendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
