/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:42:34 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.imgsceltaendpoint;

/**
 * Service definition for Imgsceltaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ImgsceltaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Imgsceltaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the imgsceltaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "imgsceltaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Imgsceltaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Imgsceltaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getImgScelta".
   *
   * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting any
   * optional parameters, call the {@link GetImgScelta#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetImgScelta getImgScelta(java.lang.Long id) throws java.io.IOException {
    GetImgScelta result = new GetImgScelta(id);
    initialize(result);
    return result;
  }

  public class GetImgScelta extends ImgsceltaendpointRequest<com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta> {

    private static final String REST_PATH = "imgscelta/{id}";

    /**
     * Create a request for the method "getImgScelta".
     *
     * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting
     * any optional parameters, call the {@link GetImgScelta#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetImgScelta#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetImgScelta(java.lang.Long id) {
      super(Imgsceltaendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetImgScelta setAlt(java.lang.String alt) {
      return (GetImgScelta) super.setAlt(alt);
    }

    @Override
    public GetImgScelta setFields(java.lang.String fields) {
      return (GetImgScelta) super.setFields(fields);
    }

    @Override
    public GetImgScelta setKey(java.lang.String key) {
      return (GetImgScelta) super.setKey(key);
    }

    @Override
    public GetImgScelta setOauthToken(java.lang.String oauthToken) {
      return (GetImgScelta) super.setOauthToken(oauthToken);
    }

    @Override
    public GetImgScelta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetImgScelta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetImgScelta setQuotaUser(java.lang.String quotaUser) {
      return (GetImgScelta) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetImgScelta setUserIp(java.lang.String userIp) {
      return (GetImgScelta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetImgScelta setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetImgScelta set(String parameterName, Object value) {
      return (GetImgScelta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertImgScelta".
   *
   * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting any
   * optional parameters, call the {@link InsertImgScelta#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta}
   * @return the request
   */
  public InsertImgScelta insertImgScelta(com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta content) throws java.io.IOException {
    InsertImgScelta result = new InsertImgScelta(content);
    initialize(result);
    return result;
  }

  public class InsertImgScelta extends ImgsceltaendpointRequest<com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta> {

    private static final String REST_PATH = "imgscelta";

    /**
     * Create a request for the method "insertImgScelta".
     *
     * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting
     * any optional parameters, call the {@link InsertImgScelta#execute()} method to invoke the remote
     * operation. <p> {@link InsertImgScelta#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta}
     * @since 1.13
     */
    protected InsertImgScelta(com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta content) {
      super(Imgsceltaendpoint.this, "POST", REST_PATH, content, com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta.class);
    }

    @Override
    public InsertImgScelta setAlt(java.lang.String alt) {
      return (InsertImgScelta) super.setAlt(alt);
    }

    @Override
    public InsertImgScelta setFields(java.lang.String fields) {
      return (InsertImgScelta) super.setFields(fields);
    }

    @Override
    public InsertImgScelta setKey(java.lang.String key) {
      return (InsertImgScelta) super.setKey(key);
    }

    @Override
    public InsertImgScelta setOauthToken(java.lang.String oauthToken) {
      return (InsertImgScelta) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertImgScelta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertImgScelta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertImgScelta setQuotaUser(java.lang.String quotaUser) {
      return (InsertImgScelta) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertImgScelta setUserIp(java.lang.String userIp) {
      return (InsertImgScelta) super.setUserIp(userIp);
    }

    @Override
    public InsertImgScelta set(String parameterName, Object value) {
      return (InsertImgScelta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listImgScelta".
   *
   * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting any
   * optional parameters, call the {@link ListImgScelta#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListImgScelta listImgScelta() throws java.io.IOException {
    ListImgScelta result = new ListImgScelta();
    initialize(result);
    return result;
  }

  public class ListImgScelta extends ImgsceltaendpointRequest<com.example.googletutorial2.imgsceltaendpoint.model.CollectionResponseImgScelta> {

    private static final String REST_PATH = "imgscelta";

    /**
     * Create a request for the method "listImgScelta".
     *
     * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting
     * any optional parameters, call the {@link ListImgScelta#execute()} method to invoke the remote
     * operation. <p> {@link ListImgScelta#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListImgScelta() {
      super(Imgsceltaendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.imgsceltaendpoint.model.CollectionResponseImgScelta.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListImgScelta setAlt(java.lang.String alt) {
      return (ListImgScelta) super.setAlt(alt);
    }

    @Override
    public ListImgScelta setFields(java.lang.String fields) {
      return (ListImgScelta) super.setFields(fields);
    }

    @Override
    public ListImgScelta setKey(java.lang.String key) {
      return (ListImgScelta) super.setKey(key);
    }

    @Override
    public ListImgScelta setOauthToken(java.lang.String oauthToken) {
      return (ListImgScelta) super.setOauthToken(oauthToken);
    }

    @Override
    public ListImgScelta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListImgScelta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListImgScelta setQuotaUser(java.lang.String quotaUser) {
      return (ListImgScelta) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListImgScelta setUserIp(java.lang.String userIp) {
      return (ListImgScelta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListImgScelta setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListImgScelta setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListImgScelta set(String parameterName, Object value) {
      return (ListImgScelta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeImgScelta".
   *
   * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting any
   * optional parameters, call the {@link RemoveImgScelta#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveImgScelta removeImgScelta(java.lang.Long id) throws java.io.IOException {
    RemoveImgScelta result = new RemoveImgScelta(id);
    initialize(result);
    return result;
  }

  public class RemoveImgScelta extends ImgsceltaendpointRequest<Void> {

    private static final String REST_PATH = "imgscelta/{id}";

    /**
     * Create a request for the method "removeImgScelta".
     *
     * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting
     * any optional parameters, call the {@link RemoveImgScelta#execute()} method to invoke the remote
     * operation. <p> {@link RemoveImgScelta#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveImgScelta(java.lang.Long id) {
      super(Imgsceltaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveImgScelta setAlt(java.lang.String alt) {
      return (RemoveImgScelta) super.setAlt(alt);
    }

    @Override
    public RemoveImgScelta setFields(java.lang.String fields) {
      return (RemoveImgScelta) super.setFields(fields);
    }

    @Override
    public RemoveImgScelta setKey(java.lang.String key) {
      return (RemoveImgScelta) super.setKey(key);
    }

    @Override
    public RemoveImgScelta setOauthToken(java.lang.String oauthToken) {
      return (RemoveImgScelta) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveImgScelta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveImgScelta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveImgScelta setQuotaUser(java.lang.String quotaUser) {
      return (RemoveImgScelta) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveImgScelta setUserIp(java.lang.String userIp) {
      return (RemoveImgScelta) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveImgScelta setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveImgScelta set(String parameterName, Object value) {
      return (RemoveImgScelta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateImgScelta".
   *
   * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting any
   * optional parameters, call the {@link UpdateImgScelta#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta}
   * @return the request
   */
  public UpdateImgScelta updateImgScelta(com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta content) throws java.io.IOException {
    UpdateImgScelta result = new UpdateImgScelta(content);
    initialize(result);
    return result;
  }

  public class UpdateImgScelta extends ImgsceltaendpointRequest<com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta> {

    private static final String REST_PATH = "imgscelta";

    /**
     * Create a request for the method "updateImgScelta".
     *
     * This request holds the parameters needed by the the imgsceltaendpoint server.  After setting
     * any optional parameters, call the {@link UpdateImgScelta#execute()} method to invoke the remote
     * operation. <p> {@link UpdateImgScelta#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta}
     * @since 1.13
     */
    protected UpdateImgScelta(com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta content) {
      super(Imgsceltaendpoint.this, "PUT", REST_PATH, content, com.example.googletutorial2.imgsceltaendpoint.model.ImgScelta.class);
    }

    @Override
    public UpdateImgScelta setAlt(java.lang.String alt) {
      return (UpdateImgScelta) super.setAlt(alt);
    }

    @Override
    public UpdateImgScelta setFields(java.lang.String fields) {
      return (UpdateImgScelta) super.setFields(fields);
    }

    @Override
    public UpdateImgScelta setKey(java.lang.String key) {
      return (UpdateImgScelta) super.setKey(key);
    }

    @Override
    public UpdateImgScelta setOauthToken(java.lang.String oauthToken) {
      return (UpdateImgScelta) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateImgScelta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateImgScelta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateImgScelta setQuotaUser(java.lang.String quotaUser) {
      return (UpdateImgScelta) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateImgScelta setUserIp(java.lang.String userIp) {
      return (UpdateImgScelta) super.setUserIp(userIp);
    }

    @Override
    public UpdateImgScelta set(String parameterName, Object value) {
      return (UpdateImgScelta) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Imgsceltaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Imgsceltaendpoint}. */
    @Override
    public Imgsceltaendpoint build() {
      return new Imgsceltaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ImgsceltaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setImgsceltaendpointRequestInitializer(
        ImgsceltaendpointRequestInitializer imgsceltaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(imgsceltaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
