/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:39:19 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.pollimageendpoint;

/**
 * Service definition for Pollimageendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PollimageendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Pollimageendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the pollimageendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "pollimageendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Pollimageendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Pollimageendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPollImage".
   *
   * This request holds the parameters needed by the the pollimageendpoint server.  After setting any
   * optional parameters, call the {@link GetPollImage#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPollImage getPollImage(java.lang.Long id) throws java.io.IOException {
    GetPollImage result = new GetPollImage(id);
    initialize(result);
    return result;
  }

  public class GetPollImage extends PollimageendpointRequest<com.example.googletutorial2.pollimageendpoint.model.PollImage> {

    private static final String REST_PATH = "pollimage/{id}";

    /**
     * Create a request for the method "getPollImage".
     *
     * This request holds the parameters needed by the the pollimageendpoint server.  After setting
     * any optional parameters, call the {@link GetPollImage#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPollImage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPollImage(java.lang.Long id) {
      super(Pollimageendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.pollimageendpoint.model.PollImage.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPollImage setAlt(java.lang.String alt) {
      return (GetPollImage) super.setAlt(alt);
    }

    @Override
    public GetPollImage setFields(java.lang.String fields) {
      return (GetPollImage) super.setFields(fields);
    }

    @Override
    public GetPollImage setKey(java.lang.String key) {
      return (GetPollImage) super.setKey(key);
    }

    @Override
    public GetPollImage setOauthToken(java.lang.String oauthToken) {
      return (GetPollImage) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPollImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPollImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPollImage setQuotaUser(java.lang.String quotaUser) {
      return (GetPollImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPollImage setUserIp(java.lang.String userIp) {
      return (GetPollImage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPollImage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPollImage set(String parameterName, Object value) {
      return (GetPollImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPollImage".
   *
   * This request holds the parameters needed by the the pollimageendpoint server.  After setting any
   * optional parameters, call the {@link InsertPollImage#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.pollimageendpoint.model.PollImage}
   * @return the request
   */
  public InsertPollImage insertPollImage(com.example.googletutorial2.pollimageendpoint.model.PollImage content) throws java.io.IOException {
    InsertPollImage result = new InsertPollImage(content);
    initialize(result);
    return result;
  }

  public class InsertPollImage extends PollimageendpointRequest<com.example.googletutorial2.pollimageendpoint.model.PollImage> {

    private static final String REST_PATH = "pollimage";

    /**
     * Create a request for the method "insertPollImage".
     *
     * This request holds the parameters needed by the the pollimageendpoint server.  After setting
     * any optional parameters, call the {@link InsertPollImage#execute()} method to invoke the remote
     * operation. <p> {@link InsertPollImage#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.pollimageendpoint.model.PollImage}
     * @since 1.13
     */
    protected InsertPollImage(com.example.googletutorial2.pollimageendpoint.model.PollImage content) {
      super(Pollimageendpoint.this, "POST", REST_PATH, content, com.example.googletutorial2.pollimageendpoint.model.PollImage.class);
    }

    @Override
    public InsertPollImage setAlt(java.lang.String alt) {
      return (InsertPollImage) super.setAlt(alt);
    }

    @Override
    public InsertPollImage setFields(java.lang.String fields) {
      return (InsertPollImage) super.setFields(fields);
    }

    @Override
    public InsertPollImage setKey(java.lang.String key) {
      return (InsertPollImage) super.setKey(key);
    }

    @Override
    public InsertPollImage setOauthToken(java.lang.String oauthToken) {
      return (InsertPollImage) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPollImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPollImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPollImage setQuotaUser(java.lang.String quotaUser) {
      return (InsertPollImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPollImage setUserIp(java.lang.String userIp) {
      return (InsertPollImage) super.setUserIp(userIp);
    }

    @Override
    public InsertPollImage set(String parameterName, Object value) {
      return (InsertPollImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPollImage".
   *
   * This request holds the parameters needed by the the pollimageendpoint server.  After setting any
   * optional parameters, call the {@link ListPollImage#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPollImage listPollImage() throws java.io.IOException {
    ListPollImage result = new ListPollImage();
    initialize(result);
    return result;
  }

  public class ListPollImage extends PollimageendpointRequest<com.example.googletutorial2.pollimageendpoint.model.CollectionResponsePollImage> {

    private static final String REST_PATH = "pollimage";

    /**
     * Create a request for the method "listPollImage".
     *
     * This request holds the parameters needed by the the pollimageendpoint server.  After setting
     * any optional parameters, call the {@link ListPollImage#execute()} method to invoke the remote
     * operation. <p> {@link ListPollImage#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPollImage() {
      super(Pollimageendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.pollimageendpoint.model.CollectionResponsePollImage.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPollImage setAlt(java.lang.String alt) {
      return (ListPollImage) super.setAlt(alt);
    }

    @Override
    public ListPollImage setFields(java.lang.String fields) {
      return (ListPollImage) super.setFields(fields);
    }

    @Override
    public ListPollImage setKey(java.lang.String key) {
      return (ListPollImage) super.setKey(key);
    }

    @Override
    public ListPollImage setOauthToken(java.lang.String oauthToken) {
      return (ListPollImage) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPollImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPollImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPollImage setQuotaUser(java.lang.String quotaUser) {
      return (ListPollImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPollImage setUserIp(java.lang.String userIp) {
      return (ListPollImage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPollImage setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPollImage setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPollImage set(String parameterName, Object value) {
      return (ListPollImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePollImage".
   *
   * This request holds the parameters needed by the the pollimageendpoint server.  After setting any
   * optional parameters, call the {@link RemovePollImage#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePollImage removePollImage(java.lang.Long id) throws java.io.IOException {
    RemovePollImage result = new RemovePollImage(id);
    initialize(result);
    return result;
  }

  public class RemovePollImage extends PollimageendpointRequest<Void> {

    private static final String REST_PATH = "pollimage/{id}";

    /**
     * Create a request for the method "removePollImage".
     *
     * This request holds the parameters needed by the the pollimageendpoint server.  After setting
     * any optional parameters, call the {@link RemovePollImage#execute()} method to invoke the remote
     * operation. <p> {@link RemovePollImage#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePollImage(java.lang.Long id) {
      super(Pollimageendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePollImage setAlt(java.lang.String alt) {
      return (RemovePollImage) super.setAlt(alt);
    }

    @Override
    public RemovePollImage setFields(java.lang.String fields) {
      return (RemovePollImage) super.setFields(fields);
    }

    @Override
    public RemovePollImage setKey(java.lang.String key) {
      return (RemovePollImage) super.setKey(key);
    }

    @Override
    public RemovePollImage setOauthToken(java.lang.String oauthToken) {
      return (RemovePollImage) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePollImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePollImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePollImage setQuotaUser(java.lang.String quotaUser) {
      return (RemovePollImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePollImage setUserIp(java.lang.String userIp) {
      return (RemovePollImage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePollImage setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePollImage set(String parameterName, Object value) {
      return (RemovePollImage) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePollImage".
   *
   * This request holds the parameters needed by the the pollimageendpoint server.  After setting any
   * optional parameters, call the {@link UpdatePollImage#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.pollimageendpoint.model.PollImage}
   * @return the request
   */
  public UpdatePollImage updatePollImage(com.example.googletutorial2.pollimageendpoint.model.PollImage content) throws java.io.IOException {
    UpdatePollImage result = new UpdatePollImage(content);
    initialize(result);
    return result;
  }

  public class UpdatePollImage extends PollimageendpointRequest<com.example.googletutorial2.pollimageendpoint.model.PollImage> {

    private static final String REST_PATH = "pollimage";

    /**
     * Create a request for the method "updatePollImage".
     *
     * This request holds the parameters needed by the the pollimageendpoint server.  After setting
     * any optional parameters, call the {@link UpdatePollImage#execute()} method to invoke the remote
     * operation. <p> {@link UpdatePollImage#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.pollimageendpoint.model.PollImage}
     * @since 1.13
     */
    protected UpdatePollImage(com.example.googletutorial2.pollimageendpoint.model.PollImage content) {
      super(Pollimageendpoint.this, "PUT", REST_PATH, content, com.example.googletutorial2.pollimageendpoint.model.PollImage.class);
    }

    @Override
    public UpdatePollImage setAlt(java.lang.String alt) {
      return (UpdatePollImage) super.setAlt(alt);
    }

    @Override
    public UpdatePollImage setFields(java.lang.String fields) {
      return (UpdatePollImage) super.setFields(fields);
    }

    @Override
    public UpdatePollImage setKey(java.lang.String key) {
      return (UpdatePollImage) super.setKey(key);
    }

    @Override
    public UpdatePollImage setOauthToken(java.lang.String oauthToken) {
      return (UpdatePollImage) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePollImage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePollImage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePollImage setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePollImage) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePollImage setUserIp(java.lang.String userIp) {
      return (UpdatePollImage) super.setUserIp(userIp);
    }

    @Override
    public UpdatePollImage set(String parameterName, Object value) {
      return (UpdatePollImage) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Pollimageendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Pollimageendpoint}. */
    @Override
    public Pollimageendpoint build() {
      return new Pollimageendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PollimageendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPollimageendpointRequestInitializer(
        PollimageendpointRequestInitializer pollimageendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(pollimageendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
