/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:42:07 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.notificaendpoint;

/**
 * Service definition for Notificaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link NotificaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Notificaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the notificaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "notificaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Notificaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Notificaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getNotifica".
   *
   * This request holds the parameters needed by the the notificaendpoint server.  After setting any
   * optional parameters, call the {@link GetNotifica#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetNotifica getNotifica(java.lang.Long id) throws java.io.IOException {
    GetNotifica result = new GetNotifica(id);
    initialize(result);
    return result;
  }

  public class GetNotifica extends NotificaendpointRequest<com.example.googletutorial2.notificaendpoint.model.Notifica> {

    private static final String REST_PATH = "notifica/{id}";

    /**
     * Create a request for the method "getNotifica".
     *
     * This request holds the parameters needed by the the notificaendpoint server.  After setting any
     * optional parameters, call the {@link GetNotifica#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetNotifica#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetNotifica(java.lang.Long id) {
      super(Notificaendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.notificaendpoint.model.Notifica.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetNotifica setAlt(java.lang.String alt) {
      return (GetNotifica) super.setAlt(alt);
    }

    @Override
    public GetNotifica setFields(java.lang.String fields) {
      return (GetNotifica) super.setFields(fields);
    }

    @Override
    public GetNotifica setKey(java.lang.String key) {
      return (GetNotifica) super.setKey(key);
    }

    @Override
    public GetNotifica setOauthToken(java.lang.String oauthToken) {
      return (GetNotifica) super.setOauthToken(oauthToken);
    }

    @Override
    public GetNotifica setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetNotifica) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetNotifica setQuotaUser(java.lang.String quotaUser) {
      return (GetNotifica) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetNotifica setUserIp(java.lang.String userIp) {
      return (GetNotifica) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetNotifica setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetNotifica set(String parameterName, Object value) {
      return (GetNotifica) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertNotifica".
   *
   * This request holds the parameters needed by the the notificaendpoint server.  After setting any
   * optional parameters, call the {@link InsertNotifica#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.notificaendpoint.model.Notifica}
   * @return the request
   */
  public InsertNotifica insertNotifica(com.example.googletutorial2.notificaendpoint.model.Notifica content) throws java.io.IOException {
    InsertNotifica result = new InsertNotifica(content);
    initialize(result);
    return result;
  }

  public class InsertNotifica extends NotificaendpointRequest<com.example.googletutorial2.notificaendpoint.model.Notifica> {

    private static final String REST_PATH = "notifica";

    /**
     * Create a request for the method "insertNotifica".
     *
     * This request holds the parameters needed by the the notificaendpoint server.  After setting any
     * optional parameters, call the {@link InsertNotifica#execute()} method to invoke the remote
     * operation. <p> {@link InsertNotifica#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.notificaendpoint.model.Notifica}
     * @since 1.13
     */
    protected InsertNotifica(com.example.googletutorial2.notificaendpoint.model.Notifica content) {
      super(Notificaendpoint.this, "POST", REST_PATH, content, com.example.googletutorial2.notificaendpoint.model.Notifica.class);
    }

    @Override
    public InsertNotifica setAlt(java.lang.String alt) {
      return (InsertNotifica) super.setAlt(alt);
    }

    @Override
    public InsertNotifica setFields(java.lang.String fields) {
      return (InsertNotifica) super.setFields(fields);
    }

    @Override
    public InsertNotifica setKey(java.lang.String key) {
      return (InsertNotifica) super.setKey(key);
    }

    @Override
    public InsertNotifica setOauthToken(java.lang.String oauthToken) {
      return (InsertNotifica) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertNotifica setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertNotifica) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertNotifica setQuotaUser(java.lang.String quotaUser) {
      return (InsertNotifica) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertNotifica setUserIp(java.lang.String userIp) {
      return (InsertNotifica) super.setUserIp(userIp);
    }

    @Override
    public InsertNotifica set(String parameterName, Object value) {
      return (InsertNotifica) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listNotifica".
   *
   * This request holds the parameters needed by the the notificaendpoint server.  After setting any
   * optional parameters, call the {@link ListNotifica#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListNotifica listNotifica() throws java.io.IOException {
    ListNotifica result = new ListNotifica();
    initialize(result);
    return result;
  }

  public class ListNotifica extends NotificaendpointRequest<com.example.googletutorial2.notificaendpoint.model.CollectionResponseNotifica> {

    private static final String REST_PATH = "notifica";

    /**
     * Create a request for the method "listNotifica".
     *
     * This request holds the parameters needed by the the notificaendpoint server.  After setting any
     * optional parameters, call the {@link ListNotifica#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListNotifica#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListNotifica() {
      super(Notificaendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.notificaendpoint.model.CollectionResponseNotifica.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListNotifica setAlt(java.lang.String alt) {
      return (ListNotifica) super.setAlt(alt);
    }

    @Override
    public ListNotifica setFields(java.lang.String fields) {
      return (ListNotifica) super.setFields(fields);
    }

    @Override
    public ListNotifica setKey(java.lang.String key) {
      return (ListNotifica) super.setKey(key);
    }

    @Override
    public ListNotifica setOauthToken(java.lang.String oauthToken) {
      return (ListNotifica) super.setOauthToken(oauthToken);
    }

    @Override
    public ListNotifica setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListNotifica) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListNotifica setQuotaUser(java.lang.String quotaUser) {
      return (ListNotifica) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListNotifica setUserIp(java.lang.String userIp) {
      return (ListNotifica) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListNotifica setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListNotifica setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListNotifica set(String parameterName, Object value) {
      return (ListNotifica) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeNotifica".
   *
   * This request holds the parameters needed by the the notificaendpoint server.  After setting any
   * optional parameters, call the {@link RemoveNotifica#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveNotifica removeNotifica(java.lang.Long id) throws java.io.IOException {
    RemoveNotifica result = new RemoveNotifica(id);
    initialize(result);
    return result;
  }

  public class RemoveNotifica extends NotificaendpointRequest<Void> {

    private static final String REST_PATH = "notifica/{id}";

    /**
     * Create a request for the method "removeNotifica".
     *
     * This request holds the parameters needed by the the notificaendpoint server.  After setting any
     * optional parameters, call the {@link RemoveNotifica#execute()} method to invoke the remote
     * operation. <p> {@link RemoveNotifica#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveNotifica(java.lang.Long id) {
      super(Notificaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveNotifica setAlt(java.lang.String alt) {
      return (RemoveNotifica) super.setAlt(alt);
    }

    @Override
    public RemoveNotifica setFields(java.lang.String fields) {
      return (RemoveNotifica) super.setFields(fields);
    }

    @Override
    public RemoveNotifica setKey(java.lang.String key) {
      return (RemoveNotifica) super.setKey(key);
    }

    @Override
    public RemoveNotifica setOauthToken(java.lang.String oauthToken) {
      return (RemoveNotifica) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveNotifica setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveNotifica) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveNotifica setQuotaUser(java.lang.String quotaUser) {
      return (RemoveNotifica) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveNotifica setUserIp(java.lang.String userIp) {
      return (RemoveNotifica) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveNotifica setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveNotifica set(String parameterName, Object value) {
      return (RemoveNotifica) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateNotifica".
   *
   * This request holds the parameters needed by the the notificaendpoint server.  After setting any
   * optional parameters, call the {@link UpdateNotifica#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.notificaendpoint.model.Notifica}
   * @return the request
   */
  public UpdateNotifica updateNotifica(com.example.googletutorial2.notificaendpoint.model.Notifica content) throws java.io.IOException {
    UpdateNotifica result = new UpdateNotifica(content);
    initialize(result);
    return result;
  }

  public class UpdateNotifica extends NotificaendpointRequest<com.example.googletutorial2.notificaendpoint.model.Notifica> {

    private static final String REST_PATH = "notifica";

    /**
     * Create a request for the method "updateNotifica".
     *
     * This request holds the parameters needed by the the notificaendpoint server.  After setting any
     * optional parameters, call the {@link UpdateNotifica#execute()} method to invoke the remote
     * operation. <p> {@link UpdateNotifica#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.notificaendpoint.model.Notifica}
     * @since 1.13
     */
    protected UpdateNotifica(com.example.googletutorial2.notificaendpoint.model.Notifica content) {
      super(Notificaendpoint.this, "PUT", REST_PATH, content, com.example.googletutorial2.notificaendpoint.model.Notifica.class);
    }

    @Override
    public UpdateNotifica setAlt(java.lang.String alt) {
      return (UpdateNotifica) super.setAlt(alt);
    }

    @Override
    public UpdateNotifica setFields(java.lang.String fields) {
      return (UpdateNotifica) super.setFields(fields);
    }

    @Override
    public UpdateNotifica setKey(java.lang.String key) {
      return (UpdateNotifica) super.setKey(key);
    }

    @Override
    public UpdateNotifica setOauthToken(java.lang.String oauthToken) {
      return (UpdateNotifica) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateNotifica setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateNotifica) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateNotifica setQuotaUser(java.lang.String quotaUser) {
      return (UpdateNotifica) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateNotifica setUserIp(java.lang.String userIp) {
      return (UpdateNotifica) super.setUserIp(userIp);
    }

    @Override
    public UpdateNotifica set(String parameterName, Object value) {
      return (UpdateNotifica) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Notificaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Notificaendpoint}. */
    @Override
    public Notificaendpoint build() {
      return new Notificaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link NotificaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setNotificaendpointRequestInitializer(
        NotificaendpointRequestInitializer notificaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(notificaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
