/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:40:35 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.utenteendpoint;

/**
 * Service definition for Utenteendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link UtenteendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Utenteendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the utenteendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "utenteendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Utenteendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Utenteendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getUtente".
   *
   * This request holds the parameters needed by the the utenteendpoint server.  After setting any
   * optional parameters, call the {@link GetUtente#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetUtente getUtente(java.lang.String id) throws java.io.IOException {
    GetUtente result = new GetUtente(id);
    initialize(result);
    return result;
  }

  public class GetUtente extends UtenteendpointRequest<com.example.googletutorial2.utenteendpoint.model.Utente> {

    private static final String REST_PATH = "utente/{id}";

    /**
     * Create a request for the method "getUtente".
     *
     * This request holds the parameters needed by the the utenteendpoint server.  After setting any
     * optional parameters, call the {@link GetUtente#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetUtente#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetUtente(java.lang.String id) {
      super(Utenteendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.utenteendpoint.model.Utente.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetUtente setAlt(java.lang.String alt) {
      return (GetUtente) super.setAlt(alt);
    }

    @Override
    public GetUtente setFields(java.lang.String fields) {
      return (GetUtente) super.setFields(fields);
    }

    @Override
    public GetUtente setKey(java.lang.String key) {
      return (GetUtente) super.setKey(key);
    }

    @Override
    public GetUtente setOauthToken(java.lang.String oauthToken) {
      return (GetUtente) super.setOauthToken(oauthToken);
    }

    @Override
    public GetUtente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetUtente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetUtente setQuotaUser(java.lang.String quotaUser) {
      return (GetUtente) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetUtente setUserIp(java.lang.String userIp) {
      return (GetUtente) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetUtente setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetUtente set(String parameterName, Object value) {
      return (GetUtente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertUtente".
   *
   * This request holds the parameters needed by the the utenteendpoint server.  After setting any
   * optional parameters, call the {@link InsertUtente#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.utenteendpoint.model.Utente}
   * @return the request
   */
  public InsertUtente insertUtente(com.example.googletutorial2.utenteendpoint.model.Utente content) throws java.io.IOException {
    InsertUtente result = new InsertUtente(content);
    initialize(result);
    return result;
  }

  public class InsertUtente extends UtenteendpointRequest<com.example.googletutorial2.utenteendpoint.model.Utente> {

    private static final String REST_PATH = "utente";

    /**
     * Create a request for the method "insertUtente".
     *
     * This request holds the parameters needed by the the utenteendpoint server.  After setting any
     * optional parameters, call the {@link InsertUtente#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertUtente#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.utenteendpoint.model.Utente}
     * @since 1.13
     */
    protected InsertUtente(com.example.googletutorial2.utenteendpoint.model.Utente content) {
      super(Utenteendpoint.this, "POST", REST_PATH, content, com.example.googletutorial2.utenteendpoint.model.Utente.class);
    }

    @Override
    public InsertUtente setAlt(java.lang.String alt) {
      return (InsertUtente) super.setAlt(alt);
    }

    @Override
    public InsertUtente setFields(java.lang.String fields) {
      return (InsertUtente) super.setFields(fields);
    }

    @Override
    public InsertUtente setKey(java.lang.String key) {
      return (InsertUtente) super.setKey(key);
    }

    @Override
    public InsertUtente setOauthToken(java.lang.String oauthToken) {
      return (InsertUtente) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertUtente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertUtente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertUtente setQuotaUser(java.lang.String quotaUser) {
      return (InsertUtente) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertUtente setUserIp(java.lang.String userIp) {
      return (InsertUtente) super.setUserIp(userIp);
    }

    @Override
    public InsertUtente set(String parameterName, Object value) {
      return (InsertUtente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listUtente".
   *
   * This request holds the parameters needed by the the utenteendpoint server.  After setting any
   * optional parameters, call the {@link ListUtente#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListUtente listUtente() throws java.io.IOException {
    ListUtente result = new ListUtente();
    initialize(result);
    return result;
  }

  public class ListUtente extends UtenteendpointRequest<com.example.googletutorial2.utenteendpoint.model.CollectionResponseUtente> {

    private static final String REST_PATH = "utente";

    /**
     * Create a request for the method "listUtente".
     *
     * This request holds the parameters needed by the the utenteendpoint server.  After setting any
     * optional parameters, call the {@link ListUtente#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListUtente#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListUtente() {
      super(Utenteendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.utenteendpoint.model.CollectionResponseUtente.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListUtente setAlt(java.lang.String alt) {
      return (ListUtente) super.setAlt(alt);
    }

    @Override
    public ListUtente setFields(java.lang.String fields) {
      return (ListUtente) super.setFields(fields);
    }

    @Override
    public ListUtente setKey(java.lang.String key) {
      return (ListUtente) super.setKey(key);
    }

    @Override
    public ListUtente setOauthToken(java.lang.String oauthToken) {
      return (ListUtente) super.setOauthToken(oauthToken);
    }

    @Override
    public ListUtente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListUtente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListUtente setQuotaUser(java.lang.String quotaUser) {
      return (ListUtente) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListUtente setUserIp(java.lang.String userIp) {
      return (ListUtente) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListUtente setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListUtente setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListUtente set(String parameterName, Object value) {
      return (ListUtente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeUtente".
   *
   * This request holds the parameters needed by the the utenteendpoint server.  After setting any
   * optional parameters, call the {@link RemoveUtente#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveUtente removeUtente(java.lang.String id) throws java.io.IOException {
    RemoveUtente result = new RemoveUtente(id);
    initialize(result);
    return result;
  }

  public class RemoveUtente extends UtenteendpointRequest<Void> {

    private static final String REST_PATH = "utente/{id}";

    /**
     * Create a request for the method "removeUtente".
     *
     * This request holds the parameters needed by the the utenteendpoint server.  After setting any
     * optional parameters, call the {@link RemoveUtente#execute()} method to invoke the remote
     * operation. <p> {@link
     * RemoveUtente#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveUtente(java.lang.String id) {
      super(Utenteendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveUtente setAlt(java.lang.String alt) {
      return (RemoveUtente) super.setAlt(alt);
    }

    @Override
    public RemoveUtente setFields(java.lang.String fields) {
      return (RemoveUtente) super.setFields(fields);
    }

    @Override
    public RemoveUtente setKey(java.lang.String key) {
      return (RemoveUtente) super.setKey(key);
    }

    @Override
    public RemoveUtente setOauthToken(java.lang.String oauthToken) {
      return (RemoveUtente) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveUtente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveUtente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveUtente setQuotaUser(java.lang.String quotaUser) {
      return (RemoveUtente) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveUtente setUserIp(java.lang.String userIp) {
      return (RemoveUtente) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveUtente setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveUtente set(String parameterName, Object value) {
      return (RemoveUtente) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateUtente".
   *
   * This request holds the parameters needed by the the utenteendpoint server.  After setting any
   * optional parameters, call the {@link UpdateUtente#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.utenteendpoint.model.Utente}
   * @return the request
   */
  public UpdateUtente updateUtente(com.example.googletutorial2.utenteendpoint.model.Utente content) throws java.io.IOException {
    UpdateUtente result = new UpdateUtente(content);
    initialize(result);
    return result;
  }

  public class UpdateUtente extends UtenteendpointRequest<com.example.googletutorial2.utenteendpoint.model.Utente> {

    private static final String REST_PATH = "utente";

    /**
     * Create a request for the method "updateUtente".
     *
     * This request holds the parameters needed by the the utenteendpoint server.  After setting any
     * optional parameters, call the {@link UpdateUtente#execute()} method to invoke the remote
     * operation. <p> {@link
     * UpdateUtente#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.utenteendpoint.model.Utente}
     * @since 1.13
     */
    protected UpdateUtente(com.example.googletutorial2.utenteendpoint.model.Utente content) {
      super(Utenteendpoint.this, "PUT", REST_PATH, content, com.example.googletutorial2.utenteendpoint.model.Utente.class);
    }

    @Override
    public UpdateUtente setAlt(java.lang.String alt) {
      return (UpdateUtente) super.setAlt(alt);
    }

    @Override
    public UpdateUtente setFields(java.lang.String fields) {
      return (UpdateUtente) super.setFields(fields);
    }

    @Override
    public UpdateUtente setKey(java.lang.String key) {
      return (UpdateUtente) super.setKey(key);
    }

    @Override
    public UpdateUtente setOauthToken(java.lang.String oauthToken) {
      return (UpdateUtente) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateUtente setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateUtente) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateUtente setQuotaUser(java.lang.String quotaUser) {
      return (UpdateUtente) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateUtente setUserIp(java.lang.String userIp) {
      return (UpdateUtente) super.setUserIp(userIp);
    }

    @Override
    public UpdateUtente set(String parameterName, Object value) {
      return (UpdateUtente) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Utenteendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Utenteendpoint}. */
    @Override
    public Utenteendpoint build() {
      return new Utenteendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link UtenteendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setUtenteendpointRequestInitializer(
        UtenteendpointRequestInitializer utenteendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(utenteendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
