/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:39:44 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.pollsharingendpoint;

/**
 * Service definition for Pollsharingendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PollsharingendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Pollsharingendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the pollsharingendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "pollsharingendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Pollsharingendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Pollsharingendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getPollSharing".
   *
   * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
   * any optional parameters, call the {@link GetPollSharing#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetPollSharing getPollSharing(java.lang.Long id) throws java.io.IOException {
    GetPollSharing result = new GetPollSharing(id);
    initialize(result);
    return result;
  }

  public class GetPollSharing extends PollsharingendpointRequest<com.example.googletutorial2.pollsharingendpoint.model.PollSharing> {

    private static final String REST_PATH = "pollsharing/{id}";

    /**
     * Create a request for the method "getPollSharing".
     *
     * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
     * any optional parameters, call the {@link GetPollSharing#execute()} method to invoke the remote
     * operation. <p> {@link GetPollSharing#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPollSharing(java.lang.Long id) {
      super(Pollsharingendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.pollsharingendpoint.model.PollSharing.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPollSharing setAlt(java.lang.String alt) {
      return (GetPollSharing) super.setAlt(alt);
    }

    @Override
    public GetPollSharing setFields(java.lang.String fields) {
      return (GetPollSharing) super.setFields(fields);
    }

    @Override
    public GetPollSharing setKey(java.lang.String key) {
      return (GetPollSharing) super.setKey(key);
    }

    @Override
    public GetPollSharing setOauthToken(java.lang.String oauthToken) {
      return (GetPollSharing) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPollSharing setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPollSharing) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPollSharing setQuotaUser(java.lang.String quotaUser) {
      return (GetPollSharing) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPollSharing setUserIp(java.lang.String userIp) {
      return (GetPollSharing) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPollSharing setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPollSharing set(String parameterName, Object value) {
      return (GetPollSharing) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPollSharing".
   *
   * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
   * any optional parameters, call the {@link InsertPollSharing#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.pollsharingendpoint.model.PollSharing}
   * @return the request
   */
  public InsertPollSharing insertPollSharing(com.example.googletutorial2.pollsharingendpoint.model.PollSharing content) throws java.io.IOException {
    InsertPollSharing result = new InsertPollSharing(content);
    initialize(result);
    return result;
  }

  public class InsertPollSharing extends PollsharingendpointRequest<com.example.googletutorial2.pollsharingendpoint.model.PollSharing> {

    private static final String REST_PATH = "pollsharing";

    /**
     * Create a request for the method "insertPollSharing".
     *
     * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
     * any optional parameters, call the {@link InsertPollSharing#execute()} method to invoke the
     * remote operation. <p> {@link InsertPollSharing#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.pollsharingendpoint.model.PollSharing}
     * @since 1.13
     */
    protected InsertPollSharing(com.example.googletutorial2.pollsharingendpoint.model.PollSharing content) {
      super(Pollsharingendpoint.this, "POST", REST_PATH, content, com.example.googletutorial2.pollsharingendpoint.model.PollSharing.class);
    }

    @Override
    public InsertPollSharing setAlt(java.lang.String alt) {
      return (InsertPollSharing) super.setAlt(alt);
    }

    @Override
    public InsertPollSharing setFields(java.lang.String fields) {
      return (InsertPollSharing) super.setFields(fields);
    }

    @Override
    public InsertPollSharing setKey(java.lang.String key) {
      return (InsertPollSharing) super.setKey(key);
    }

    @Override
    public InsertPollSharing setOauthToken(java.lang.String oauthToken) {
      return (InsertPollSharing) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPollSharing setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPollSharing) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPollSharing setQuotaUser(java.lang.String quotaUser) {
      return (InsertPollSharing) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPollSharing setUserIp(java.lang.String userIp) {
      return (InsertPollSharing) super.setUserIp(userIp);
    }

    @Override
    public InsertPollSharing set(String parameterName, Object value) {
      return (InsertPollSharing) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPollSharing".
   *
   * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
   * any optional parameters, call the {@link ListPollSharing#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPollSharing listPollSharing() throws java.io.IOException {
    ListPollSharing result = new ListPollSharing();
    initialize(result);
    return result;
  }

  public class ListPollSharing extends PollsharingendpointRequest<com.example.googletutorial2.pollsharingendpoint.model.CollectionResponsePollSharing> {

    private static final String REST_PATH = "pollsharing";

    /**
     * Create a request for the method "listPollSharing".
     *
     * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
     * any optional parameters, call the {@link ListPollSharing#execute()} method to invoke the remote
     * operation. <p> {@link ListPollSharing#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPollSharing() {
      super(Pollsharingendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.pollsharingendpoint.model.CollectionResponsePollSharing.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPollSharing setAlt(java.lang.String alt) {
      return (ListPollSharing) super.setAlt(alt);
    }

    @Override
    public ListPollSharing setFields(java.lang.String fields) {
      return (ListPollSharing) super.setFields(fields);
    }

    @Override
    public ListPollSharing setKey(java.lang.String key) {
      return (ListPollSharing) super.setKey(key);
    }

    @Override
    public ListPollSharing setOauthToken(java.lang.String oauthToken) {
      return (ListPollSharing) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPollSharing setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPollSharing) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPollSharing setQuotaUser(java.lang.String quotaUser) {
      return (ListPollSharing) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPollSharing setUserIp(java.lang.String userIp) {
      return (ListPollSharing) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListPollSharing setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListPollSharing setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListPollSharing set(String parameterName, Object value) {
      return (ListPollSharing) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removePollSharing".
   *
   * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
   * any optional parameters, call the {@link RemovePollSharing#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemovePollSharing removePollSharing(java.lang.Long id) throws java.io.IOException {
    RemovePollSharing result = new RemovePollSharing(id);
    initialize(result);
    return result;
  }

  public class RemovePollSharing extends PollsharingendpointRequest<Void> {

    private static final String REST_PATH = "pollsharing/{id}";

    /**
     * Create a request for the method "removePollSharing".
     *
     * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
     * any optional parameters, call the {@link RemovePollSharing#execute()} method to invoke the
     * remote operation. <p> {@link RemovePollSharing#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemovePollSharing(java.lang.Long id) {
      super(Pollsharingendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemovePollSharing setAlt(java.lang.String alt) {
      return (RemovePollSharing) super.setAlt(alt);
    }

    @Override
    public RemovePollSharing setFields(java.lang.String fields) {
      return (RemovePollSharing) super.setFields(fields);
    }

    @Override
    public RemovePollSharing setKey(java.lang.String key) {
      return (RemovePollSharing) super.setKey(key);
    }

    @Override
    public RemovePollSharing setOauthToken(java.lang.String oauthToken) {
      return (RemovePollSharing) super.setOauthToken(oauthToken);
    }

    @Override
    public RemovePollSharing setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemovePollSharing) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemovePollSharing setQuotaUser(java.lang.String quotaUser) {
      return (RemovePollSharing) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemovePollSharing setUserIp(java.lang.String userIp) {
      return (RemovePollSharing) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemovePollSharing setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemovePollSharing set(String parameterName, Object value) {
      return (RemovePollSharing) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updatePollSharing".
   *
   * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
   * any optional parameters, call the {@link UpdatePollSharing#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.pollsharingendpoint.model.PollSharing}
   * @return the request
   */
  public UpdatePollSharing updatePollSharing(com.example.googletutorial2.pollsharingendpoint.model.PollSharing content) throws java.io.IOException {
    UpdatePollSharing result = new UpdatePollSharing(content);
    initialize(result);
    return result;
  }

  public class UpdatePollSharing extends PollsharingendpointRequest<com.example.googletutorial2.pollsharingendpoint.model.PollSharing> {

    private static final String REST_PATH = "pollsharing";

    /**
     * Create a request for the method "updatePollSharing".
     *
     * This request holds the parameters needed by the the pollsharingendpoint server.  After setting
     * any optional parameters, call the {@link UpdatePollSharing#execute()} method to invoke the
     * remote operation. <p> {@link UpdatePollSharing#initialize(com.google.api.client.googleapis.serv
     * ices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.pollsharingendpoint.model.PollSharing}
     * @since 1.13
     */
    protected UpdatePollSharing(com.example.googletutorial2.pollsharingendpoint.model.PollSharing content) {
      super(Pollsharingendpoint.this, "PUT", REST_PATH, content, com.example.googletutorial2.pollsharingendpoint.model.PollSharing.class);
    }

    @Override
    public UpdatePollSharing setAlt(java.lang.String alt) {
      return (UpdatePollSharing) super.setAlt(alt);
    }

    @Override
    public UpdatePollSharing setFields(java.lang.String fields) {
      return (UpdatePollSharing) super.setFields(fields);
    }

    @Override
    public UpdatePollSharing setKey(java.lang.String key) {
      return (UpdatePollSharing) super.setKey(key);
    }

    @Override
    public UpdatePollSharing setOauthToken(java.lang.String oauthToken) {
      return (UpdatePollSharing) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdatePollSharing setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdatePollSharing) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdatePollSharing setQuotaUser(java.lang.String quotaUser) {
      return (UpdatePollSharing) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdatePollSharing setUserIp(java.lang.String userIp) {
      return (UpdatePollSharing) super.setUserIp(userIp);
    }

    @Override
    public UpdatePollSharing set(String parameterName, Object value) {
      return (UpdatePollSharing) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Pollsharingendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Pollsharingendpoint}. */
    @Override
    public Pollsharingendpoint build() {
      return new Pollsharingendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PollsharingendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPollsharingendpointRequestInitializer(
        PollsharingendpointRequestInitializer pollsharingendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(pollsharingendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
