/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:40:57 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.pollendpoint.model;

/**
 * Model definition for Poll.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the pollendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Poll extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String chiuso;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String creatore;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime dataCr;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key keyPoll;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String titolo;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getChiuso() {
    return chiuso;
  }

  /**
   * @param chiuso chiuso or {@code null} for none
   */
  public Poll setChiuso(java.lang.String chiuso) {
    this.chiuso = chiuso;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCreatore() {
    return creatore;
  }

  /**
   * @param creatore creatore or {@code null} for none
   */
  public Poll setCreatore(java.lang.String creatore) {
    this.creatore = creatore;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDataCr() {
    return dataCr;
  }

  /**
   * @param dataCr dataCr or {@code null} for none
   */
  public Poll setDataCr(com.google.api.client.util.DateTime dataCr) {
    this.dataCr = dataCr;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKeyPoll() {
    return keyPoll;
  }

  /**
   * @param keyPoll keyPoll or {@code null} for none
   */
  public Poll setKeyPoll(Key keyPoll) {
    this.keyPoll = keyPoll;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTitolo() {
    return titolo;
  }

  /**
   * @param titolo titolo or {@code null} for none
   */
  public Poll setTitolo(java.lang.String titolo) {
    this.titolo = titolo;
    return this;
  }

  @Override
  public Poll set(String fieldName, Object value) {
    return (Poll) super.set(fieldName, value);
  }

  @Override
  public Poll clone() {
    return (Poll) super.clone();
  }

}
