/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:42:34 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.imgsceltaendpoint.model;

/**
 * Model definition for ImgScelta.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the imgsceltaendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ImgScelta extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key immagine;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key keyIS;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key keyImg;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key keyPoll;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String utente;

  /**
   * @return value or {@code null} for none
   */
  public Key getImmagine() {
    return immagine;
  }

  /**
   * @param immagine immagine or {@code null} for none
   */
  public ImgScelta setImmagine(Key immagine) {
    this.immagine = immagine;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKeyIS() {
    return keyIS;
  }

  /**
   * @param keyIS keyIS or {@code null} for none
   */
  public ImgScelta setKeyIS(Key keyIS) {
    this.keyIS = keyIS;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKeyImg() {
    return keyImg;
  }

  /**
   * @param keyImg keyImg or {@code null} for none
   */
  public ImgScelta setKeyImg(Key keyImg) {
    this.keyImg = keyImg;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKeyPoll() {
    return keyPoll;
  }

  /**
   * @param keyPoll keyPoll or {@code null} for none
   */
  public ImgScelta setKeyPoll(Key keyPoll) {
    this.keyPoll = keyPoll;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUtente() {
    return utente;
  }

  /**
   * @param utente utente or {@code null} for none
   */
  public ImgScelta setUtente(java.lang.String utente) {
    this.utente = utente;
    return this;
  }

  @Override
  public ImgScelta set(String fieldName, Object value) {
    return (ImgScelta) super.set(fieldName, value);
  }

  @Override
  public ImgScelta clone() {
    return (ImgScelta) super.clone();
  }

}
