/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:40:10 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.amiciziaendpoint;

/**
 * Service definition for Amiciziaendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AmiciziaendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Amiciziaendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the amiciziaendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "amiciziaendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Amiciziaendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Amiciziaendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAmicizia".
   *
   * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
   * optional parameters, call the {@link GetAmicizia#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetAmicizia getAmicizia(java.lang.Long id) throws java.io.IOException {
    GetAmicizia result = new GetAmicizia(id);
    initialize(result);
    return result;
  }

  public class GetAmicizia extends AmiciziaendpointRequest<com.example.googletutorial2.amiciziaendpoint.model.Amicizia> {

    private static final String REST_PATH = "amicizia/{id}";

    /**
     * Create a request for the method "getAmicizia".
     *
     * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
     * optional parameters, call the {@link GetAmicizia#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetAmicizia#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAmicizia(java.lang.Long id) {
      super(Amiciziaendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.amiciziaendpoint.model.Amicizia.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAmicizia setAlt(java.lang.String alt) {
      return (GetAmicizia) super.setAlt(alt);
    }

    @Override
    public GetAmicizia setFields(java.lang.String fields) {
      return (GetAmicizia) super.setFields(fields);
    }

    @Override
    public GetAmicizia setKey(java.lang.String key) {
      return (GetAmicizia) super.setKey(key);
    }

    @Override
    public GetAmicizia setOauthToken(java.lang.String oauthToken) {
      return (GetAmicizia) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAmicizia setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAmicizia) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAmicizia setQuotaUser(java.lang.String quotaUser) {
      return (GetAmicizia) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAmicizia setUserIp(java.lang.String userIp) {
      return (GetAmicizia) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetAmicizia setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAmicizia set(String parameterName, Object value) {
      return (GetAmicizia) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAmicizia".
   *
   * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
   * optional parameters, call the {@link InsertAmicizia#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.amiciziaendpoint.model.Amicizia}
   * @return the request
   */
  public InsertAmicizia insertAmicizia(com.example.googletutorial2.amiciziaendpoint.model.Amicizia content) throws java.io.IOException {
    InsertAmicizia result = new InsertAmicizia(content);
    initialize(result);
    return result;
  }

  public class InsertAmicizia extends AmiciziaendpointRequest<com.example.googletutorial2.amiciziaendpoint.model.Amicizia> {

    private static final String REST_PATH = "amicizia";

    /**
     * Create a request for the method "insertAmicizia".
     *
     * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
     * optional parameters, call the {@link InsertAmicizia#execute()} method to invoke the remote
     * operation. <p> {@link InsertAmicizia#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.amiciziaendpoint.model.Amicizia}
     * @since 1.13
     */
    protected InsertAmicizia(com.example.googletutorial2.amiciziaendpoint.model.Amicizia content) {
      super(Amiciziaendpoint.this, "POST", REST_PATH, content, com.example.googletutorial2.amiciziaendpoint.model.Amicizia.class);
    }

    @Override
    public InsertAmicizia setAlt(java.lang.String alt) {
      return (InsertAmicizia) super.setAlt(alt);
    }

    @Override
    public InsertAmicizia setFields(java.lang.String fields) {
      return (InsertAmicizia) super.setFields(fields);
    }

    @Override
    public InsertAmicizia setKey(java.lang.String key) {
      return (InsertAmicizia) super.setKey(key);
    }

    @Override
    public InsertAmicizia setOauthToken(java.lang.String oauthToken) {
      return (InsertAmicizia) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAmicizia setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAmicizia) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAmicizia setQuotaUser(java.lang.String quotaUser) {
      return (InsertAmicizia) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAmicizia setUserIp(java.lang.String userIp) {
      return (InsertAmicizia) super.setUserIp(userIp);
    }

    @Override
    public InsertAmicizia set(String parameterName, Object value) {
      return (InsertAmicizia) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAmicizia".
   *
   * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
   * optional parameters, call the {@link ListAmicizia#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAmicizia listAmicizia() throws java.io.IOException {
    ListAmicizia result = new ListAmicizia();
    initialize(result);
    return result;
  }

  public class ListAmicizia extends AmiciziaendpointRequest<com.example.googletutorial2.amiciziaendpoint.model.CollectionResponseAmicizia> {

    private static final String REST_PATH = "amicizia";

    /**
     * Create a request for the method "listAmicizia".
     *
     * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
     * optional parameters, call the {@link ListAmicizia#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListAmicizia#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAmicizia() {
      super(Amiciziaendpoint.this, "GET", REST_PATH, null, com.example.googletutorial2.amiciziaendpoint.model.CollectionResponseAmicizia.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAmicizia setAlt(java.lang.String alt) {
      return (ListAmicizia) super.setAlt(alt);
    }

    @Override
    public ListAmicizia setFields(java.lang.String fields) {
      return (ListAmicizia) super.setFields(fields);
    }

    @Override
    public ListAmicizia setKey(java.lang.String key) {
      return (ListAmicizia) super.setKey(key);
    }

    @Override
    public ListAmicizia setOauthToken(java.lang.String oauthToken) {
      return (ListAmicizia) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAmicizia setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAmicizia) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAmicizia setQuotaUser(java.lang.String quotaUser) {
      return (ListAmicizia) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAmicizia setUserIp(java.lang.String userIp) {
      return (ListAmicizia) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAmicizia setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAmicizia setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAmicizia set(String parameterName, Object value) {
      return (ListAmicizia) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAmicizia".
   *
   * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAmicizia#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAmicizia removeAmicizia(java.lang.Long id) throws java.io.IOException {
    RemoveAmicizia result = new RemoveAmicizia(id);
    initialize(result);
    return result;
  }

  public class RemoveAmicizia extends AmiciziaendpointRequest<Void> {

    private static final String REST_PATH = "amicizia/{id}";

    /**
     * Create a request for the method "removeAmicizia".
     *
     * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
     * optional parameters, call the {@link RemoveAmicizia#execute()} method to invoke the remote
     * operation. <p> {@link RemoveAmicizia#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAmicizia(java.lang.Long id) {
      super(Amiciziaendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAmicizia setAlt(java.lang.String alt) {
      return (RemoveAmicizia) super.setAlt(alt);
    }

    @Override
    public RemoveAmicizia setFields(java.lang.String fields) {
      return (RemoveAmicizia) super.setFields(fields);
    }

    @Override
    public RemoveAmicizia setKey(java.lang.String key) {
      return (RemoveAmicizia) super.setKey(key);
    }

    @Override
    public RemoveAmicizia setOauthToken(java.lang.String oauthToken) {
      return (RemoveAmicizia) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAmicizia setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAmicizia) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAmicizia setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAmicizia) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAmicizia setUserIp(java.lang.String userIp) {
      return (RemoveAmicizia) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveAmicizia setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAmicizia set(String parameterName, Object value) {
      return (RemoveAmicizia) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAmicizia".
   *
   * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAmicizia#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.example.googletutorial2.amiciziaendpoint.model.Amicizia}
   * @return the request
   */
  public UpdateAmicizia updateAmicizia(com.example.googletutorial2.amiciziaendpoint.model.Amicizia content) throws java.io.IOException {
    UpdateAmicizia result = new UpdateAmicizia(content);
    initialize(result);
    return result;
  }

  public class UpdateAmicizia extends AmiciziaendpointRequest<com.example.googletutorial2.amiciziaendpoint.model.Amicizia> {

    private static final String REST_PATH = "amicizia";

    /**
     * Create a request for the method "updateAmicizia".
     *
     * This request holds the parameters needed by the the amiciziaendpoint server.  After setting any
     * optional parameters, call the {@link UpdateAmicizia#execute()} method to invoke the remote
     * operation. <p> {@link UpdateAmicizia#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.example.googletutorial2.amiciziaendpoint.model.Amicizia}
     * @since 1.13
     */
    protected UpdateAmicizia(com.example.googletutorial2.amiciziaendpoint.model.Amicizia content) {
      super(Amiciziaendpoint.this, "PUT", REST_PATH, content, com.example.googletutorial2.amiciziaendpoint.model.Amicizia.class);
    }

    @Override
    public UpdateAmicizia setAlt(java.lang.String alt) {
      return (UpdateAmicizia) super.setAlt(alt);
    }

    @Override
    public UpdateAmicizia setFields(java.lang.String fields) {
      return (UpdateAmicizia) super.setFields(fields);
    }

    @Override
    public UpdateAmicizia setKey(java.lang.String key) {
      return (UpdateAmicizia) super.setKey(key);
    }

    @Override
    public UpdateAmicizia setOauthToken(java.lang.String oauthToken) {
      return (UpdateAmicizia) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAmicizia setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAmicizia) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAmicizia setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAmicizia) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAmicizia setUserIp(java.lang.String userIp) {
      return (UpdateAmicizia) super.setUserIp(userIp);
    }

    @Override
    public UpdateAmicizia set(String parameterName, Object value) {
      return (UpdateAmicizia) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Amiciziaendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Amiciziaendpoint}. */
    @Override
    public Amiciziaendpoint build() {
      return new Amiciziaendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AmiciziaendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAmiciziaendpointRequestInitializer(
        AmiciziaendpointRequestInitializer amiciziaendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(amiciziaendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
