/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:40:10 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.amiciziaendpoint.model;

/**
 * Model definition for Amicizia.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the amiciziaendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Amicizia extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime dataRich;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String destinatario;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key keyA;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mittente;

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getDataRich() {
    return dataRich;
  }

  /**
   * @param dataRich dataRich or {@code null} for none
   */
  public Amicizia setDataRich(com.google.api.client.util.DateTime dataRich) {
    this.dataRich = dataRich;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDestinatario() {
    return destinatario;
  }

  /**
   * @param destinatario destinatario or {@code null} for none
   */
  public Amicizia setDestinatario(java.lang.String destinatario) {
    this.destinatario = destinatario;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKeyA() {
    return keyA;
  }

  /**
   * @param keyA keyA or {@code null} for none
   */
  public Amicizia setKeyA(Key keyA) {
    this.keyA = keyA;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMittente() {
    return mittente;
  }

  /**
   * @param mittente mittente or {@code null} for none
   */
  public Amicizia setMittente(java.lang.String mittente) {
    this.mittente = mittente;
    return this;
  }

  @Override
  public Amicizia set(String fieldName, Object value) {
    return (Amicizia) super.set(fieldName, value);
  }

  @Override
  public Amicizia clone() {
    return (Amicizia) super.clone();
  }

}
