/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-12-19 23:55:21 UTC)
 * on 2013-12-28 at 17:40:35 UTC 
 * Modify at your own risk.
 */

package com.example.googletutorial2.utenteendpoint.model;

/**
 * Model definition for Utente.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the utenteendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Utente extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cap;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String citta;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cognome;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime data;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String email;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key image;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key img;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String istruzione;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nazione;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nome;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String provincia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pwd;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sesso;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String statoCiv;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCap() {
    return cap;
  }

  /**
   * @param cap cap or {@code null} for none
   */
  public Utente setCap(java.lang.String cap) {
    this.cap = cap;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCitta() {
    return citta;
  }

  /**
   * @param citta citta or {@code null} for none
   */
  public Utente setCitta(java.lang.String citta) {
    this.citta = citta;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCognome() {
    return cognome;
  }

  /**
   * @param cognome cognome or {@code null} for none
   */
  public Utente setCognome(java.lang.String cognome) {
    this.cognome = cognome;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getData() {
    return data;
  }

  /**
   * @param data data or {@code null} for none
   */
  public Utente setData(com.google.api.client.util.DateTime data) {
    this.data = data;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEmail() {
    return email;
  }

  /**
   * @param email email or {@code null} for none
   */
  public Utente setEmail(java.lang.String email) {
    this.email = email;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getImage() {
    return image;
  }

  /**
   * @param image image or {@code null} for none
   */
  public Utente setImage(Key image) {
    this.image = image;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getImg() {
    return img;
  }

  /**
   * @param img img or {@code null} for none
   */
  public Utente setImg(Key img) {
    this.img = img;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIstruzione() {
    return istruzione;
  }

  /**
   * @param istruzione istruzione or {@code null} for none
   */
  public Utente setIstruzione(java.lang.String istruzione) {
    this.istruzione = istruzione;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNazione() {
    return nazione;
  }

  /**
   * @param nazione nazione or {@code null} for none
   */
  public Utente setNazione(java.lang.String nazione) {
    this.nazione = nazione;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNome() {
    return nome;
  }

  /**
   * @param nome nome or {@code null} for none
   */
  public Utente setNome(java.lang.String nome) {
    this.nome = nome;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getProvincia() {
    return provincia;
  }

  /**
   * @param provincia provincia or {@code null} for none
   */
  public Utente setProvincia(java.lang.String provincia) {
    this.provincia = provincia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPwd() {
    return pwd;
  }

  /**
   * @param pwd pwd or {@code null} for none
   */
  public Utente setPwd(java.lang.String pwd) {
    this.pwd = pwd;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSesso() {
    return sesso;
  }

  /**
   * @param sesso sesso or {@code null} for none
   */
  public Utente setSesso(java.lang.String sesso) {
    this.sesso = sesso;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatoCiv() {
    return statoCiv;
  }

  /**
   * @param statoCiv statoCiv or {@code null} for none
   */
  public Utente setStatoCiv(java.lang.String statoCiv) {
    this.statoCiv = statoCiv;
    return this;
  }

  @Override
  public Utente set(String fieldName, Object value) {
    return (Utente) super.set(fieldName, value);
  }

  @Override
  public Utente clone() {
    return (Utente) super.clone();
  }

}
